# NumPy

*Numerical Python* or *Numpy* is a 3rd-party python library which deals with homogeneous data objects namely arrays. It also provides support for storing,manuipulating,performing high-level mathematical operations for the same in a large amount.

In [23]:
import numpy as np
np.__version__

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

'1.19.5'

## Create ndArrays from scratch

Numpy allows creation of *n-dimentional Arrays* or *ndArrays* with various methods like:
- Using `numpy.array()` method with a Python Lists
- Using `numpy.zeros()` method to produce an array filled with zeroes, of desired size
- Using `numpy.ones()` method to produce an array filled with ones, of desired size
- Using `numpy.arange()` method, which is quite similar to the bulit-in range function, but with support for floating-point numbers
- Using `numpy.linspace()` method to produce an array of uniformly spaced numbers, of desired size
- Using `numpy.full()` method to produce an array with the same value, of desired size
- Using `numpy.empty()` method to produce an uninitialized array of desired size with values which already exist at the corresponding memory location(s)
- Using `numpy.eye()` method to produce an identity matrix of desired size
- Using the `numpy.random` module


In [24]:
np.array([1,2,3,4,5])
np.array([1,2.2,3,4,5])
# here using dtype=int produces an integer ndarray instead of the default float32
np.array([1,2,3,4.4,5],dtype='int32')
np.array([range(i,i+3) for i in range(1,4)])

array([1, 2, 3, 4, 5])

array([1. , 2.2, 3. , 4. , 5. ])

array([1, 2, 3, 4, 5])

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [25]:
# Produces an array filled with 0s

np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
# Produces an array filled with 1s

np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
# Similar to the built-in range function but with support for floating point numbers

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
# Return a uniformly-spaced number array

np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [29]:
# Fills and returns an array with the same number

np.full((4,4),2.5)

array([[2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5]])

In [30]:
# Create an uninitialized array of three integers 
# The values will be whatever happens to already exist at that 
# memory location

np.empty((2,4))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 7.23312106e-321, 7.74528464e-312,
        7.74528464e-312]])

In [31]:
# Create and identity matrix of given size

np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### The Random module


In [32]:
# normally distributed random values 
# with mean 0 and standard deviation 1

np.random.normal(1,10,(3,3))

array([[ -3.75776001,  15.40731118, -10.49075681],
       [  9.05714552,  18.5610703 ,  10.72979914],
       [-14.51119112,   2.91143478,  17.04776071]])

In [33]:
# uniformly distributed 
# random values between 0 and 1

np.random.random((3,3))

array([[0.47486752, 0.47013219, 0.71607453],
       [0.287991  , 0.38346223, 0.74916984],
       [0.87845219, 0.10286336, 0.09237389]])

In [34]:
# Fill an array with random values between the given high and low

np.random.randint(0,10,(3,4,5))

array([[[9, 1, 6, 8, 8],
        [3, 2, 3, 6, 3],
        [6, 5, 7, 0, 8],
        [4, 6, 5, 8, 2]],

       [[3, 9, 7, 5, 3],
        [4, 5, 3, 3, 7],
        [9, 9, 9, 7, 3],
        [2, 3, 9, 7, 7]],

       [[5, 1, 2, 2, 8],
        [1, 5, 8, 4, 0],
        [2, 5, 5, 0, 8],
        [1, 1, 0, 3, 8]]])

## Array Attributes

Some useful array attributes are:<br>

1. `.ndim` , returns the count(n) of the dimensions of an ndArray
2. `.shape`, returns the dimensions of an array
3. `.size`, return the total items in an array
4. `.dtype`, return the data type of the elements of an array
5. `.itemsize`, return the size of an individual item in an array
6. `.nbytes`, returns the total size of an array, including all its elements

In [35]:
np.random.seed(0)
arr=np.random.randint(0,10,(3,4,5))
print("Array Dimension Count: ",arr.ndim)
print("Array Shape: ",arr.shape)
print("Array Size: ",arr.size)
print("Array Data type: ",arr.dtype)
print("Array individual item size: ",arr.itemsize)
print("Array Size in bytes: ",arr.nbytes)

Array Dimension Count:  3
Array Shape:  (3, 4, 5)
Array Size:  60
Array Data type:  int32
Array individual item size:  4
Array Size in bytes:  240


## Array Indexing
 
 Array indexing in numpy is done in the following ways:
 - For 1-D arrays, indexing is same as the built-in pyhton list indexing with the index passed between square brackets after the array literal.
 - For multi-dimensional arrays, indices are passed between square brackets, seperated by commas

*Note: Value assignment can be easily done by using the assignment operator, `=`*

In [36]:
arr_1d=np.random.randint(1,10,4)
arr_2d=np.random.randint(1,10,(4,4))
arr_3d=np.random.randint(1,10,(4,4,4))
print("1-D array:\n",arr_1d)
print("Indices [1] and [3] ->",arr_1d[1],"&",arr_1d[-1])
print("\n2-D array:\n",arr_2d)
print("Indices [1,1] and [3,3] ->",arr_2d[1,1],"&",arr_2d[-1,-1])
print("\n3-D array:\n",arr_3d)
print("Indices [1,1,1] and [2,2,2] and [3,3,3] ->",arr_3d[1,1,1],"&",arr_3d[2,2,2],"&",arr_3d[-1,-1,-1])

1-D array:
 [9 2 2 8]
Indices [1] and [3] -> 2 & 8

2-D array:
 [[4 7 8 3]
 [1 4 6 5]
 [5 7 5 5]
 [4 5 5 9]]
Indices [1,1] and [3,3] -> 4 & 9

3-D array:
 [[[5 4 8 6]
  [6 1 2 6]
  [4 1 6 1]
  [2 3 5 3]]

 [[1 4 3 1]
  [8 6 1 3]
  [8 3 3 4]
  [4 3 4 5]]

 [[2 3 2 5]
  [7 9 3 4]
  [1 1 7 1]
  [7 4 4 9]]

 [[9 9 3 4]
  [3 1 9 9]
  [4 9 3 9]
  [5 4 1 5]]]
Indices [1,1,1] and [2,2,2] and [3,3,3] -> 6 & 7 & 5


## Array Slicing

Array slicing or accessing sub-arrays in numpy can be done in the following ways:
- For 1-D arrays, slicing is similar to that in built-in python lists, using the syntax, `arr[start:stop:step]`
- For multi-dimensional arrays, slicing can be done identically as in 1-D array but with the difference of comma-seperated slice for each dimension. > e.g. for an array of ndim as 2,  `arr[start:stop:step,start:stop:step]`

*Note: When a parameter of a slice is left empty,numpy slices assert the same behaviour as the python list slices i.e. to use the default value for that field. This is a very common practice, used while accesing a single column in an array.*


In [37]:
print(arr_1d)
print("1-D array, item 1 to 2 ->",arr_1d[1:3])
print(arr_2d)
print("2-D array, row 2 to 3 and all columns but reversed ->\n",arr_2d[2:,::-1])
print("2-D array, row 3       ->",arr_2d[3])
print("2-D array, row 2       ->",arr_2d[2])
# Accessing single column with empty slices
print("2-D array, last Column ->",arr_2d[:,-1])
print("2-D array, Column 2    ->",arr_2d[:,2])

[9 2 2 8]
1-D array, item 1 to 2 -> [2 2]
[[4 7 8 3]
 [1 4 6 5]
 [5 7 5 5]
 [4 5 5 9]]
2-D array, row 2 to 3 and all columns but reversed ->
 [[5 5 7 5]
 [9 5 5 4]]
2-D array, row 3       -> [4 5 5 9]
2-D array, row 2       -> [5 7 5 5]
2-D array, last Column -> [3 5 5 9]
2-D array, Column 2    -> [8 6 5 5]


>*Note: One way in which numpy array slices differ from python list slices is that, instead of returning a copy of the subarray, a numpy array slice returns a view of the subarray. This is intended behaviour, because this allows easy manipulation of subarrays. To avoid this, use the `.copy()` method of numpy arrays to return a copy of the subarray and prevent any further confusion.*

In [38]:
print("Initial array:")
print(arr_1d)
tempArray=arr_1d.copy()
subArray=arr_1d[2::-1]
subArray+=1
print("Modified sub-array causes changes in the original array:")
print(arr_1d)
arr_1d=tempArray
subArray=arr_1d[2::-1].copy()
subArray+=1
print("Modified copy of sub-array causes no changes in the original array:")
print(arr_1d)

Initial array:
[9 2 2 8]
Modified sub-array causes changes in the original array:
[10  3  3  8]
Modified copy of sub-array causes no changes in the original array:
[9 2 2 8]


## Array Reshaping
Changing the dimensions of an array is termed as reshaping in numpy terminology. This is done using the `.reshape()` method and passing the desired dimensions as an argument in the form of a tuple. A common use case of this is in converting a 1-D array to a 2-D array.

In [39]:
print("Column Vector ->\n",np.arange(1,4).reshape((3,1)))
print("Row Vector ->",np.arange(1,4).reshape((1,3)))

Column Vector ->
 [[1]
 [2]
 [3]]
Row Vector -> [[1 2 3]]


*Note: Another way to convert 1-D array to 2-D is by using the `numpy.newaxis` keyword and using array slicing*

In [40]:
print("Column Vector ->\n",np.arange(1,4)[:,np.newaxis])
print("Row Vector ->",np.arange(1,4)[np.newaxis,:])

Column Vector ->
 [[1]
 [2]
 [3]]
Row Vector -> [[1 2 3]]


## Array Concatenation & Splitting

1. Concatenation can be done between numpy arrays with the help of `numpy.concatenate()` method. This method requires a list of arrays to be concatenated and takes an optional argument *axis* to specify the axis of concatenation.

>Alternatively, use `numpy.hstack()` or `numpy.vstack()` methods to improve code clarity and obtain horizontally or vertically concatenated arrays, respectively.

2. Splitting can be done on an array with the help of `numpy.split()` method. This method requires two arguments namely:
- A numpy array `Arr`
- A list of split indices or a single integer *N* (to split the array into *N* equal parts)

 An optional argument *axis* can also be provided to specify the axis to split along

>Alternatively, use `numpy.hsplit()` or `numpy.vsplit()` or `numpy.dsplit()` methods to improve code clarity and obtain horizontally or vertically or 3rd-axis split arrays, respectively.

In [41]:
a1=np.arange(1,7)
a2=np.arange(7,13)
a3=np.concatenate((a1,a2))
print("1-D Array Concatenation ->\n",a3)
a1=a1.reshape(2,3)
a2=a2.reshape(2,3)
a4=np.concatenate([a1,a2])
print("2-D Array Concatenation(Row-wise Concatenation) ->\n",a4)
print("2-D Array Concatenation(Column-wise Concatenation) ->\n",np.concatenate([a1,a2],axis=1))
# the above statement is similar to the below
print("2-D Array Concatenation(HStack Concatenation) ->\n",np.hstack([a1,a2]))

1-D Array Concatenation ->
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
2-D Array Concatenation(Row-wise Concatenation) ->
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2-D Array Concatenation(Column-wise Concatenation) ->
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
2-D Array Concatenation(HStack Concatenation) ->
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [48]:
print("Original 1-D array ->",a3)
print("Splitting in 6 equal parts ->",np.split(a3,6))
print("Splitting in at indices 5 & 8 ->",np.split(a3,[5,8]))

print("\nOriginal 2-D array ->\n",a4)
print("Splitting in 4 equal parts(Row-wise) ->")
np.split(a4,4)
print("Splitting in at indices 1,3(Row-wise) ->")
np.split(a4,[1,3])
print("Splitting in 3 equal parts(Column-wise) ->")
np.split(a4,3,axis=1) 
print("Splitting in 2 equal parts(VSplit) ->")
np.vsplit(a4,2)

Original 1-D array -> [ 1  2  3  4  5  6  7  8  9 10 11 12]
Splitting in 6 equal parts -> [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10]), array([11, 12])]
Splitting in at indices 5 & 8 -> [array([1, 2, 3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11, 12])]

Original 2-D array ->
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Splitting in 4 equal parts(Row-wise) ->


[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

Splitting in at indices 1,3(Row-wise) ->


[array([[1, 2, 3]]),
 array([[4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12]])]

Splitting in 3 equal parts(Column-wise) ->


[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

Splitting in 2 equal parts(VSplit) ->


[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]