# Numpy Arrays and their Manipulation


In [7]:
import numpy as np
arr1=np.arange(1,10) # arange(start(inclusive),stop(exclisive),step)
arr2=np.arange(6,dtype=np.float32,step=1.5)
print("Reshaped Array 2 as 2x2:",arr2.reshape(2,2),sep="\n")
print("Array 1's Shape:",arr1.shape,sep="\n")
print("Array 1:",arr1,sep="\n")
arr1=arr1.reshape(3,3) # Doesn't change the original array
arr1.resize(3,3) # Changes the original array
print("Array 1's Shape:",arr1.shape,sep="\n")
print("Array 1:",arr1,sep="\n")
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array 3's Shape:",arr3.shape,sep="\n")
print("Array 3:",arr3,sep="\n")
# linspace(start(inclusive),stop(inclusive),num,retstep=True(difference btw each element))
arr4=np.linspace(1,10,4,retstep=True)
print("Array 4:",arr4,sep="\n")
# linspace(start(inclusive),stop(exclusive, if endpoint=False),num(number of elemts in array))
arr5=np.linspace(1,10,4,endpoint=False) 
print("Array 5:",arr5,sep="\n")


Reshaped Array 2 as 2x2:
[[0.  1.5]
 [3.  4.5]]
Array 1's Shape:
(9,)
Array 1:
[1 2 3 4 5 6 7 8 9]
Array 1's Shape:
(3, 3)
Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 3's Shape:
(3, 3)
Array 3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 4:
(array([ 1.,  4.,  7., 10.]), np.float64(3.0))
Array 5:
[1.   3.25 5.5  7.75]


In [8]:
# DTypes in Numpy

dt=np.dtype([("Name",np.str_,16),("isEmployed",np.bool_),("BoostPercentage",np.float32)])
arrNew=np.array([("Satyam",True,100.0),("Ravi",False,200.0),],dtype=dt)
print(arrNew.dtype)

# ? -> bool
# < -> stored by least significant bit
# Here string type has a length, while bool and float doesn't

[('Name', '<U16'), ('isEmployed', '?'), ('BoostPercentage', '<f4')]


In [9]:
# Array Creation Methods

array1=np.empty(5,dtype=np.float32)
print("Array 1:",array1,sep="\n")
multiArr1=np.empty((5,5),dtype=np.int16)
print("Multi-Dimensional Array 1:",multiArr1,sep="\n")
print("Ones_Like Array:",np.ones_like(multiArr1),sep="\n") 
array2=np.zeros(5,dtype=np.float32)
print("Array 2:",array2,sep="\n")
multiArr2=np.zeros((5,5),dtype=np.int16)
print("Multi-Dimensional Array 2:",multiArr2,sep="\n")
array3=np.ones(5,dtype=np.float32)
print("Array 3:",array3,sep="\n")
multiArr3=np.ones((5,5),dtype=np.int16)
print("Multi-Dimensional Array 3:",multiArr3,sep="\n")
print("Empty_Like Array:",np.empty_like(multiArr3),sep="\n") 
array4=np.eye(3,dtype=np.int16)
print("Identity Array:",array4,sep="\n")
print("Full_Like Array:",np.full_like(multiArr3,10),sep="\n")

Array 1:
[1. 1. 1. 1. 1.]
Multi-Dimensional Array 1:
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
Ones_Like Array:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Array 2:
[0. 0. 0. 0. 0.]
Multi-Dimensional Array 2:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Array 3:
[1. 1. 1. 1. 1.]
Multi-Dimensional Array 3:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Empty_Like Array:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Identity Array:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Full_Like Array:
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [10]:
# Function of numpy

newArr=np.array([1,2,3,4,5,6,7,8,9,10])
print(newArr)
print("Sum = ",np.sum(newArr))
print("Product = ",np.prod(newArr))
newArr1=np.array([[1,2],[3,4]])
print(np.sum(newArr1,axis=1))
print(np.sum(newArr1,axis=0))
print(np.sum(newArr1))
print(newArr1.flatten("C")) # Array is flatted into 1-deminsional array, Row-Major
print(newArr1.flatten("F")) # Array is flatted into 1-deminsional array, Column-Major
print(np.prod(newArr1,axis=1))
print(np.prod(newArr1,axis=0))
print(np.prod(newArr1))

[ 1  2  3  4  5  6  7  8  9 10]
Sum =  55
Product =  3628800
[3 7]
[4 6]
10
[1 2 3 4]
[1 3 2 4]
[ 2 12]
[3 8]
24


In [11]:
myNewArr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
diag=np.diag(myNewArr1)
print("Diagonals:",diag,sep="\n")
print("New Diagonal Array:",np.diagflat(diag),sep="\n")
print("Triangular Array:",np.tri(5,5,dtype=np.int16,k=0),sep="\n")
print("Triangular Array w/ Offset:",np.tri(5,5,dtype=np.int16,k=1),sep="\n")
print("Lower Triangular Array:",np.tril(newArr1),sep="\n")
print("Upper Triangular Array:",np.triu(newArr1),sep="\n")


Diagonals:
[1 5 9]
New Diagonal Array:
[[1 0 0]
 [0 5 0]
 [0 0 9]]
Triangular Array:
[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]
Triangular Array w/ Offset:
[[1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Lower Triangular Array:
[[1 0]
 [3 4]]
Upper Triangular Array:
[[1 2]
 [0 4]]


## Array Manipulation

In [12]:
newArr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("New Array:",newArr2,sep="\n")
newArr3=newArr2.view()
print("New Array w/ View:",newArr3,sep="\n")
newArr4=newArr2.copy()  # np.copy(newArr2)
print("New Array w/ Copy:",newArr4,sep="\n")
newArr2[0][2]=0  # Change made in original array
print("Check for changes in View:",newArr3,sep="\n")
print("Check for changes in Copy:",newArr4,sep="\n")

New Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
New Array w/ View:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
New Array w/ Copy:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Check for changes in View:
[[1 2 0]
 [4 5 6]
 [7 8 9]]
Check for changes in Copy:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
myArr1=np.array([1,2,3,4,5,6,7,8])
myArr2=np.array([9,10,11,12,13,14,15,16])
print("Array 1: ",myArr1,sep="\n")
print("Array 2: ",myArr2,sep="\n")
print(np.append(myArr1,myArr2))
print(np.concatenate([myArr1]+[myArr2],axis=0))
print("----------------------------")
myArr3=np.array([[1,2],[3,4]])
myArr4=np.array([[5,6],[7,8]])
print("Array 3: ",myArr3,sep="\n")
print("Array 4: ",myArr1,sep="\n")
print(np.append(myArr3,myArr4,axis=0))
print(np.append(myArr3,myArr4,axis=1))
print(np.concatenate([myArr3,myArr4]))
myArr3[:,[0,1]]=myArr3[:,[1,0]]
print("Array 3 columns swapped:",myArr3,sep="\n")

Array 1: 
[1 2 3 4 5 6 7 8]
Array 2: 
[ 9 10 11 12 13 14 15 16]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
----------------------------
Array 3: 
[[1 2]
 [3 4]]
Array 4: 
[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Array 3 columns swapped:
[[2 1]
 [4 3]]


In [14]:
arr_2D = np.arange(5*5).reshape(5, 5)
print(arr_2D.shape)
arr_5D = arr_2D[np.newaxis,np.newaxis,np.newaxis]
print(arr_5D.shape)
print(arr_5D)
x = np.zeros((3, 4))
y = np.expand_dims(x, axis=0)
print(y)

(5, 5)
(1, 1, 1, 5, 5)
[[[[[ 0  1  2  3  4]
    [ 5  6  7  8  9]
    [10 11 12 13 14]
    [15 16 17 18 19]
    [20 21 22 23 24]]]]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


## Array Operations

In [15]:
# Array Operations in Numpy
print("Array 1:",arr1,sep="\n")
print("Array 1:",arr2,sep="\n")
print("Array Addition:")
print(arr1+arr3) # np.add(arr1,arr3)
print("Array Subtraction:")
print(arr3-arr1) # np.subtract(arr1,arr3)
print("Array Multiplication:")
print(arr3*arr1) # np.multiply(arr1,arr3)
print("Array Division:")
print(arr1/arr3) # np.divide(arr1,arr3)
print("Array Power:")
print(arr1**2) # np.power(arr1,2)
print("Array Mod/Remainder:")
print(arr1%2) # np.mod(arr1,2) or np.remainder(arr1,2)
print("Reciprocal of Array 3:")
print(np.reciprocal(arr3))
print("Array Transpose:")
print(arr1.T) # np.transpose(arr1)

Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 1:
[0.  1.5 3.  4.5]
Array Addition:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Array Subtraction:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Array Multiplication:
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Array Division:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array Power:
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Array Mod/Remainder:
[[1 0 1]
 [0 1 0]
 [1 0 1]]
Reciprocal of Array 3:
[[1 0 0]
 [0 0 0]
 [0 0 0]]
Array Transpose:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [16]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(arr<5)
print(arr+5)
print(arr-5)
print(arr*5)
print(arr/5)

[ 1  2  3  4  5  6  7  8  9 10]
[ True  True  True  True False False False False False False]
[ 6  7  8  9 10 11 12 13 14 15]
[-4 -3 -2 -1  0  1  2  3  4  5]
[ 5 10 15 20 25 30 35 40 45 50]
[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]


In [34]:
# Hstack, Vstack and Stack

marksArray1=np.array([1,2,3,4,5])
marksArray2=np.array([6,7,8,9,10])
dataArray1=np.array(["Satyam",10.0,10])
dataArray2=np.array(["Anurag",20.0,10])
print("Hstack and Vstack:")
print(np.hstack([marksArray1,marksArray2])) # Arr1 + Arr2
print(np.vstack([dataArray1,dataArray2]))
# Arr1
#  +
# Arr2
print("Concatenate:")
print(np.concatenate([marksArray1,marksArray2],axis=0)) # Yields the same output as hstack
print(np.concatenate([[dataArray1],[dataArray2]],axis=0)) # Yields the same output as vstack
view1=np.array([[1,2,3],["S","A","T"]])
view2=np.array([[4,5,6],["Y","A","M"]])
dataArray3=np.array([["Satyam",10.0,10],["Anurag",20.0,10]])
dataArray4=np.array([["Tushar",9.0,7],["Akmal",10.0,9]])
print("Hstack and Vstack:")
print(np.hstack([view1,view2])) # Arr3 + Arr4
print(np.vstack([dataArray3,dataArray4]))
#  Arr1
#   +
#  Arr2
print("Concatenate:")
print(np.concatenate([view1,view2],axis=1)) # Yields the same output as hstack
print(np.concatenate([dataArray3,dataArray4],axis=0)) # Yields the same output as vstack

# In stack always a new axis is added
print("Stack:")
print(np.stack([dataArray1,dataArray2],axis=0))
print(np.stack([dataArray1,dataArray2],axis=1))
print("Dstack:")
print(np.dstack([dataArray1,dataArray2]))

Hstack and Vstack:
[ 1  2  3  4  5  6  7  8  9 10]
[['Satyam' '10.0' '10']
 ['Anurag' '20.0' '10']]
Concatenate:
[ 1  2  3  4  5  6  7  8  9 10]
[['Satyam' '10.0' '10']
 ['Anurag' '20.0' '10']]
Hstack and Vstack:
[['1' '2' '3' '4' '5' '6']
 ['S' 'A' 'T' 'Y' 'A' 'M']]
[['Satyam' '10.0' '10']
 ['Anurag' '20.0' '10']
 ['Tushar' '9.0' '7']
 ['Akmal' '10.0' '9']]
Concatenate:
[['1' '2' '3' '4' '5' '6']
 ['S' 'A' 'T' 'Y' 'A' 'M']]
[['Satyam' '10.0' '10']
 ['Anurag' '20.0' '10']
 ['Tushar' '9.0' '7']
 ['Akmal' '10.0' '9']]
Stack:
[['Satyam' '10.0' '10']
 ['Anurag' '20.0' '10']]
[['Satyam' 'Anurag']
 ['10.0' '20.0']
 ['10' '10']]
Dstack:
[[['Satyam' 'Anurag']
  ['10.0' '20.0']
  ['10' '10']]]


In [18]:
num_1d = np.arange(2) 
print("One dimensional array:") 
print(num_1d) 
  
num_2d = np.arange(12).reshape(6,2) 
print("\nTwo dimensional array:") 
print(num_2d) 

for a, b in np.nditer([num_1d, num_2d]): 
    print(f"{a}:{b}")

One dimensional array:
[0 1]

Two dimensional array:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
0:0
1:1
0:2
1:3
0:4
1:5
0:6
1:7
0:8
1:9
0:10
1:11


In [19]:
# Splitting an Array

arrMy1=np.array([[1,2],[3,4]])
print(np.array_split(arrMy1,4))  #Never gives error and provides empty arrays instead
arrMy2=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.array_split(arrMy2,5))
print(np.split(arrMy1,2,axis=1))
print(np.split(arrMy2,2,axis=0))

print("VSplit:")
matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])
print(np.vsplit(matrix, 2))
print("HSplit:")
array = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(np.hsplit(array, 2))

[array([[1, 2]]), array([[3, 4]]), array([], shape=(0, 2), dtype=int64), array([], shape=(0, 2), dtype=int64)]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]
[array([[1],
       [3]]), array([[2],
       [4]])]
[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
VSplit:
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]
HSplit:
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [20]:
# Comparison Operators
# Always returns a boolean array

from functools import reduce

array1=np.array([1,2,3])
array2=np.array([1,2,4])
equal=array1==array2  # np.array_equal(array1,array2)
print(equal.all())  # True if all elements are True, else False
greater=array1>array2  # np.greater(arra1,array2)
print(greater.all())  # True if all elements are True, else False
lesser=array1<array2  # np.less(array1,array2)
print(lesser.all())  # True if all elements are True, else False
greater_equal=array1>=array2  # np.greater_equal(array1,array2)
print(greater_equal.all())  # True if all elements are True, else False
lesser_equal=array1<=array2  # np.less_equal(array1,array2)
print(lesser_equal.all())  # True if all elements are True, else False

# 1-d Array
print(np.union1d(array1,array2))
array3 = np.array([[1, 2, 3], [4, 5, 6]]) 
array4 = np.array([0, 5, 10]) 
print(np.union1d(array3,array4))

  
# Union of more than two arrays using reduce function
array5 = reduce(np.union1d, ([1, 2, 3], [1, 3, 5], 
                            [2, 4, 6], [0, 0, 0])) 
print(array5)

False
False
False
False
True
[1 2 3 4]
[ 0  1  2  3  4  5  6 10]
[0 1 2 3 4 5 6]


In [21]:
arr2D = np.array([[11, 11, 12, 11],
                     [13, 11, 12, 11],
                     [16, 11, 12, 11],
                     [11, 11, 12, 11]])
 
print('Original Array :' ,
      arr2D, sep = '\n')
 
print("Unique Elemets: ",np.unique(arr2D))
print("Unique Rows",np.unique(arr2D, axis = 0),sep='\n')
print("Unique Rows by Column",np.unique(arr2D, axis = 1),sep='\n')

# Trim-Zeroes
arr1D = np.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0)) 
arr1D=np.trim_zeros(arr1D)
print(arr1D) 

thisArr=np.zeros((1,2,3,4))
print(thisArr)
print(np.moveaxis(thisArr,0,-1))
print(np.swapaxes(thisArr,0,1))
                        

Original Array :
[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]
 [11 11 12 11]]
Unique Elemets:  [11 12 13 16]
Unique Rows
[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]]
Unique Rows by Column
[[11 11 12]
 [11 13 12]
 [11 16 12]
 [11 11 12]]
[ 1  5  7  0  6  2  9  0 10]
[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]
[[[[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]]]
[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]


## Array Slicing and Indexing

In [22]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=a[2:5] # Slicing always retuns a view or shallow copy of the array
c=a[0]  # Indexing always returns a copy of the value at that index of the array
b[0]=0
c=0
print(a)

# Slicing with start:stop:step
print(a[4:8:2])
print(a[4:])
print(a[4:-1])

# Slicing using ellipsis

d = np.array([[[1, 2, 3],[4, 5, 6]], 
            [[7, 8, 9],[10, 11, 12]]]) 
print(d[::,:4,1:3])
print(d[:,1])
print(d.shape)
# The ellipsis (...) is a shorthand for selecting all preceding dimensions
print(d[...,1])
print(d[::,::,1])

[ 1  2  0  4  5  6  7  8  9 10]
[5 7]
[ 5  6  7  8  9 10]
[5 6 7 8 9]
[[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]
[[ 4  5  6]
 [10 11 12]]
(2, 2, 3)
[[ 2  5]
 [ 8 11]]
[[ 2  5]
 [ 8 11]]


In [23]:
# Advanced Indexing

yourArr=np.array([[1,2],[3,4],[5,6]])
print(yourArr[[0,1,2],[0,0,1]])
print(yourArr[[0,2]])
yourArr1=np.array([1,2,3,4,5,6,7,8,9,10])
print(yourArr1[yourArr1>5])
print(yourArr[yourArr.sum(-1)>7])

# Use numpy.compress to select elements based on the condition
print(np.compress([0,1,1],yourArr,axis=0))
print(np.compress([False,True],yourArr,axis=1))

[1 3 6]
[[1 2]
 [5 6]]
[ 6  7  8  9 10]
[[5 6]]
[[3 4]
 [5 6]]
[[2]
 [4]
 [6]]


In [24]:
# Calculate Calories for each macronutrient

macros = np.array([ 
  [0.8, 2.9, 3.9], 
  [52.4, 23.6, 36.5], 
  [55.2, 31.7, 23.9], 
  [14.4, 11, 4.9] 
   ]) 
  
result = np.zeros_like(macros) 
  
cal_per_macro = np.array([3, 3, 8]) 
  
for i in range(macros.shape[0]): 
    result[i] = macros[i] * cal_per_macro 
  
print(result )

[[  2.4   8.7  31.2]
 [157.2  70.8 292. ]
 [165.6  95.1 191.2]
 [ 43.2  33.   39.2]]
