# Python Operations in Numpy

In [51]:
import numpy as np
arr1=np.arange(9)
arr2=np.arange(6,dtype=np.float32,step=1.5)
print(arr2.reshape(2,2))
print(arr1.shape)
print(arr1)
arr1=arr1.reshape(3,3)
print(arr1.shape)
print("Array 1:")
print(arr1)

arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3.shape)
print("Array 3:")
print(arr3)


[[0.  1.5]
 [3.  4.5]]
(9,)
[0 1 2 3 4 5 6 7 8]
(3, 3)
Array 1:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
Array 3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
# Array Operations in Numpy

print("Array Addition:")
print(arr1+arr3) # np.add(arr1,arr3)
print("Array Subtraction:")
print(arr3-arr1) # np.subtract(arr1,arr3)
print("Array Multiplication:")
print(arr3*arr1) # np.multiply(arr1,arr3)
print("Array Division:")
print(arr1/arr3) # np.divide(arr1,arr3)
print("Array Power:")
print(arr1**2) # np.power(arr1,2)
print("Array Mod/Remainder:")
print(arr1%2) # np.mod(arr1,2) or np.remainder(arr1,2)
print("Reciprocal of Array 3:")
print(np.reciprocal(arr3))
print("Array Transpose:")
print(arr1.T) # np.transpose(arr1)

Array Addition:
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
Array Subtraction:
[[1 1 1]
 [1 1 1]
 [1 1 1]]
Array Multiplication:
[[ 0  2  6]
 [12 20 30]
 [42 56 72]]
Array Division:
[[0.         0.5        0.66666667]
 [0.75       0.8        0.83333333]
 [0.85714286 0.875      0.88888889]]
Array Power:
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
Array Mod/Remainder:
[[0 1 0]
 [1 0 1]
 [0 1 0]]
Reciprocal of Array 3:
[[1 0 0]
 [0 0 0]
 [0 0 0]]
Array Transpose:
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [ ]:
# Matrix Operations in Numpy

mat1=np.matrix([[0,1,2],[3,4,5]])
print(mat1)
mat2=np.matrix([[1,2,3],[4,5,6]])
mat3=np.matrix([[1,2],[3,4],[5,6]])
print(mat2)
print(mat1+mat2) # Shape must match
print(mat2-mat1) # Shape must match
print(mat1*mat3) # Number of Col of Arr1 = Number of Row of Arr2, (2,3)*(3,2)=(2,2)
print(mat1/mat2) # Shape must match
print(mat1*mat1.T)



[[0 1 2]
 [3 4 5]]
[[1 2 3]
 [4 5 6]]
[[ 1  3  5]
 [ 7  9 11]]
[[1 1 1]
 [1 1 1]]
[[13 16]
 [40 52]]
[[0.         0.5        0.66666667]
 [0.75       0.8        0.83333333]]
[[ 5 14]
 [14 50]]


In [74]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(arr<5)
print(arr+5)
print(arr-5)
print(arr*5)
print(arr/5)


[ 1  2  3  4  5  6  7  8  9 10]
[ True  True  True  True False False False False False False]
[ 6  7  8  9 10 11 12 13 14 15]
[-4 -3 -2 -1  0  1  2  3  4  5]
[ 5 10 15 20 25 30 35 40 45 50]
[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]


In [80]:
# Function of numpy

newArr=np.array([1,2,3,4,5,6,7,8,9,10])
print(newArr)
print("Sum = ",np.sum(newArr))
newArr1=np.array([[1,2],[3,4]])
print(np.sum(newArr1,axis=1))
print(np.sum(newArr1,axis=0))
print(np.sum(newArr1))

[ 1  2  3  4  5  6  7  8  9 10]
Sum =  55
[3 7]
[4 6]
10
