# Python Operations and Numpy Arrays


In [2]:
import numpy as np
arr1=np.arange(1,10) # arange(start(inclusive),stop(exclisive),step)
arr2=np.arange(6,dtype=np.float32,step=1.5)
print("Reshaped Array 2 as 2x2:",arr2.reshape(2,2),sep="\n")
print("Array 1's Shape:",arr1.shape,sep="\n")
print("Array 1:",arr1,sep="\n")
arr1=arr1.reshape(3,3)
print("Array 1's Shape:",arr1.shape,sep="\n")
print("Array 1:",arr1,sep="\n")
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array 3's Shape:",arr3.shape,sep="\n")
print("Array 3:",arr3,sep="\n")
# linspace(start(inclusive),stop(inclusive),num,retstep=True(difference btw each element))
arr4=np.linspace(1,10,4,retstep=True)
print("Array 4:",arr4,sep="\n")
# linspace(start(inclusive),stop(exclusive, if endpoint=False),num(number of elemts in array))
arr5=np.linspace(1,10,4,endpoint=False) 
print("Array 5:",arr5,sep="\n")


Reshaped Array 2 as 2x2:
[[0.  1.5]
 [3.  4.5]]
Array 1's Shape:
(9,)
Array 1:
[1 2 3 4 5 6 7 8 9]
Array 1's Shape:
(3, 3)
Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 3's Shape:
(3, 3)
Array 3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 4:
(array([ 1.,  4.,  7., 10.]), np.float64(3.0))
Array 5:
[1.   3.25 5.5  7.75]


In [3]:
# DTypes in Numpy

dt=np.dtype([("Name",np.str_,16),("isEmployed",np.bool_),("BoostPercentage",np.float32)])
arrNew=np.array([("Satyam",True,100.0),("Ravi",False,200.0),],dtype=dt)
print(arrNew.dtype)

# ? -> bool
# < -> stored by least significant bit
# Here string type has a length, while bool and float doesn't

[('Name', '<U16'), ('isEmployed', '?'), ('BoostPercentage', '<f4')]


In [4]:
# Array Creation Methods

array1=np.empty(5,dtype=np.float32)
print("Array 1:",array1,sep="\n")
multiArr1=np.empty((5,5),dtype=np.int16)
print("Multi-Dimensional Array 1:",multiArr1,sep="\n")
print("Ones_Like Array:",np.ones_like(multiArr1),sep="\n") 
array2=np.zeros(5,dtype=np.float32)
print("Array 2:",array2,sep="\n")
multiArr2=np.zeros((5,5),dtype=np.int16)
print("Multi-Dimensional Array 2:",multiArr2,sep="\n")
array3=np.ones(5,dtype=np.float32)
print("Array 3:",array3,sep="\n")
multiArr3=np.ones((5,5),dtype=np.int16)
print("Multi-Dimensional Array 3:",multiArr3,sep="\n")
print("Empty_Like Array:",np.empty_like(multiArr3),sep="\n") 
array4=np.eye(3,dtype=np.int16)
print("Identity Array:",array4,sep="\n")
print("Full_Like Array:",np.full_like(multiArr3,10),sep="\n")

Array 1:
[4.7986757e+30 3.4756504e-15 4.6017423e+30 2.0198901e-19 1.7749589e+28]
Multi-Dimensional Array 1:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Ones_Like Array:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Array 2:
[0. 0. 0. 0. 0.]
Multi-Dimensional Array 2:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Array 3:
[1. 1. 1. 1. 1.]
Multi-Dimensional Array 3:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Empty_Like Array:
[[    0     0     0     0     0]
 [  256     0  1024     0 17152]
 [    0 29440    30     0   124]
 [  106   100   373  3442   124]
 [  106   416   356   628   673]]
Identity Array:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Full_Like Array:
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [5]:
# Matrix Operations in Numpy

mat1=np.matrix([[0,1,2],[3,4,5]])
print("Matrix 1:",mat1,sep="\n")
mat2=np.matrix([[1,2,3],[4,5,6]])
mat3=np.matrix([[1,2],[3,4],[5,6]])
print("Matrix 2:",mat2,sep="\n")
print("Matrix 1 + Matrix 2:",mat1+mat2,sep="\n") # Shape must match
print("Matrix 1 - Matrix 2:",mat1-mat2,sep="\n") # Shape must match
print("Matrix 1 * Matrix 3:",mat1*mat3,sep="\n") # Number of Col of Arr1 = Number of Row of Arr2, (2,3)*(3,2)=(2,2)
print("Matrix 1 / Matrix 2:",mat1/mat2,sep="\n") # Shape must match
print("Matrix 1 * Transpose of Matrix 1:",mat1*mat1.T,sep="\n")



Matrix 1:
[[0 1 2]
 [3 4 5]]
Matrix 2:
[[1 2 3]
 [4 5 6]]
Matrix 1 + Matrix 2:
[[ 1  3  5]
 [ 7  9 11]]
Matrix 1 - Matrix 2:
[[-1 -1 -1]
 [-1 -1 -1]]
Matrix 1 * Matrix 3:
[[13 16]
 [40 52]]
Matrix 1 / Matrix 2:
[[0.         0.5        0.66666667]
 [0.75       0.8        0.83333333]]
Matrix 1 * Transpose of Matrix 1:
[[ 5 14]
 [14 50]]


In [6]:
# Function of numpy

newArr=np.array([1,2,3,4,5,6,7,8,9,10])
print(newArr)
print("Sum = ",np.sum(newArr))
newArr1=np.array([[1,2],[3,4]])
print(np.sum(newArr1,axis=1))
print(np.sum(newArr1,axis=0))
print(np.sum(newArr1))
print(newArr1.flatten("C")) # Array is flatted into 1-deminsional array, Row-Major
print(newArr1.flatten("F")) # Array is flatted into 1-deminsional array, Column-Major

[ 1  2  3  4  5  6  7  8  9 10]
Sum =  55
[3 7]
[4 6]
10
[1 2 3 4]
[1 3 2 4]


In [7]:
myNewArr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
diag=np.diag(myNewArr1)
print("Diagonals:",diag,sep="\n")
print("New Diagonal Array:",np.diagflat(diag),sep="\n")
print("Triangular Array:",np.tri(5,5,dtype=np.int16,k=0),sep="\n")
print("Triangular Array w/ Offset:",np.tri(5,5,dtype=np.int16,k=1),sep="\n")
print("Lower Triangular Array:",np.tril(newArr1),sep="\n")
print("Upper Triangular Array:",np.triu(newArr1),sep="\n")


Diagonals:
[1 5 9]
New Diagonal Array:
[[1 0 0]
 [0 5 0]
 [0 0 9]]
Triangular Array:
[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]
Triangular Array w/ Offset:
[[1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Lower Triangular Array:
[[1 0]
 [3 4]]
Upper Triangular Array:
[[1 2]
 [0 4]]


## Array Manipulation

In [8]:
newArr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("New Array:",newArr2,sep="\n")
newArr3=newArr2.view()
print("New Array w/ View:",newArr3,sep="\n")
newArr4=newArr2.copy()  # np.copy(newArr2)
print("New Array w/ Copy:",newArr4,sep="\n")
newArr2[0][2]=0  # Change made in original array
print("Check for changes in View:",newArr3,sep="\n")
print("Check for changes in Copy:",newArr4,sep="\n")

New Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
New Array w/ View:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
New Array w/ Copy:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Check for changes in View:
[[1 2 0]
 [4 5 6]
 [7 8 9]]
Check for changes in Copy:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
myArr1=np.array([1,2,3,4,5,6,7,8])
myArr2=np.array([9,10,11,12,13,14,15,16])
print("Array 1: ",myArr1,sep="\n")
print("Array 2: ",myArr2,sep="\n")
print(np.append(myArr1,myArr2))
print(np.concatenate([myArr1]+[myArr2],axis=0))
print("----------------------------")
myArr3=np.array([[1,2],[3,4]])
myArr4=np.array([[5,6],[7,8]])
print("Array 3: ",myArr3,sep="\n")
print("Array 4: ",myArr1,sep="\n")
print(np.append(myArr3,myArr4,axis=0))
print(np.append(myArr3,myArr4,axis=1))
print(np.concatenate([myArr3,myArr4]))
myArr3[:,[0,1]]=myArr3[:,[1,0]]
print("Array 3 columns swapped:",myArr3,sep="\n")

Array 1: 
[1 2 3 4 5 6 7 8]
Array 2: 
[ 9 10 11 12 13 14 15 16]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
----------------------------
Array 3: 
[[1 2]
 [3 4]]
Array 4: 
[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Array 3 columns swapped:
[[2 1]
 [4 3]]


In [45]:
arr_2D = np.arange(5*5).reshape(5, 5)
print(arr_2D.shape)
arr_5D = arr_2D[np.newaxis,np.newaxis,np.newaxis]
print(arr_5D.shape)
print(arr_5D)
x = np.zeros((3, 4))
y = np.expand_dims(x, axis=0)
print(y)

(5, 5)
(1, 1, 1, 5, 5)
[[[[[ 0  1  2  3  4]
    [ 5  6  7  8  9]
    [10 11 12 13 14]
    [15 16 17 18 19]
    [20 21 22 23 24]]]]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


## Array Operations

In [ ]:
# Array Operations in Numpy
print("Array 1:",arr1,sep="\n")
print("Array 1:",arr2,sep="\n")
print("Array Addition:")
print(arr1+arr3) # np.add(arr1,arr3)
print("Array Subtraction:")
print(arr3-arr1) # np.subtract(arr1,arr3)
print("Array Multiplication:")
print(arr3*arr1) # np.multiply(arr1,arr3)
print("Array Division:")
print(arr1/arr3) # np.divide(arr1,arr3)
print("Array Power:")
print(arr1**2) # np.power(arr1,2)
print("Array Mod/Remainder:")
print(arr1%2) # np.mod(arr1,2) or np.remainder(arr1,2)
print("Reciprocal of Array 3:")
print(np.reciprocal(arr3))
print("Array Transpose:")
print(arr1.T) # np.transpose(arr1)

Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 1:
[0.  1.5 3.  4.5]
Array Addition:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Array Subtraction:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Array Multiplication:
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Array Division:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array Power:
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Array Mod/Remainder:
[[1 0 1]
 [0 1 0]
 [1 0 1]]
Reciprocal of Array 3:
[[1 0 0]
 [0 0 0]
 [0 0 0]]
Array Transpose:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(arr<5)
print(arr+5)
print(arr-5)
print(arr*5)
print(arr/5)

[ 1  2  3  4  5  6  7  8  9 10]
[ True  True  True  True False False False False False False]
[ 6  7  8  9 10 11 12 13 14 15]
[-4 -3 -2 -1  0  1  2  3  4  5]
[ 5 10 15 20 25 30 35 40 45 50]
[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]
