# Numpy Matrices and their Manipulation

In [47]:
# Matrix creation
import numpy as np
import numpy.matlib as mat

matrix1=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(mat.empty((3,3)))
print(mat.zeros((2,2)))
print(mat.ones((3,3),dtype=np.int16))
print(mat.eye(2,4)) # Returns matrix of any size
print(mat.identity(3)) # Always returns a square matrix


[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]]
[[0. 0.]
 [0. 0.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [48]:
# Matrix Operations in Numpy

mat1=np.matrix([[0,1,2],[3,4,5]])
print("Matrix 1:",mat1,sep="\n")
mat2=np.matrix([[1,2,3],[4,5,6]])
mat3=np.matrix([[1,2],[3,4],[5,6]])
print("Matrix 2:",mat2,sep="\n")
print("Matrix 1 + Matrix 2:",mat1+mat2,sep="\n") # Shape must match, np.add(mat1,mat2)
print("Matrix 1 - Matrix 2:",mat1-mat2,sep="\n") # Shape must match, mp.subtract(mat1,mat2)
print("Matrix 1 * Matrix 3:",mat1*mat3,sep="\n") # Number of Col of Arr1 = Number of Row of Arr2, (2,3)*(3,2)=(2,2)
print("Matrix 1 / Matrix 2:",mat1/mat2,sep="\n") # Shape must match, np.divide(mat1,mat2)
print("Matrix 1 * Transpose of Matrix 1:",mat1*mat1.T,sep="\n")

arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5,6],[7,8,9]])
arr3=np.array([[7,8],[1,2],[3,4]])
print("Array 1:",arr1,sep="\n")
print("Array 2:",arr2,sep="\n")
print("Array 3:",arr3,sep="\n")
print("Arr1 * Arr2:",np.multiply(arr1,arr2),sep="\n")  # Normal Multiplication
print("Arr1.Arr2:",np.dot(arr1,arr3),sep="\n") # Matrix dot product



Matrix 1:
[[0 1 2]
 [3 4 5]]
Matrix 2:
[[1 2 3]
 [4 5 6]]
Matrix 1 + Matrix 2:
[[ 1  3  5]
 [ 7  9 11]]
Matrix 1 - Matrix 2:
[[-1 -1 -1]
 [-1 -1 -1]]
Matrix 1 * Matrix 3:
[[13 16]
 [40 52]]
Matrix 1 / Matrix 2:
[[0.         0.5        0.66666667]
 [0.75       0.8        0.83333333]]
Matrix 1 * Transpose of Matrix 1:
[[ 5 14]
 [14 50]]
Array 1:
[[1 2 3]
 [4 5 6]]
Array 2:
[[4 5 6]
 [7 8 9]]
Array 3:
[[7 8]
 [1 2]
 [3 4]]
Arr1 * Arr2:
[[ 4 10 18]
 [28 40 54]]
Arr1.Arr2:
[[18 24]
 [51 66]]


In [55]:
matt1=np.matrix([[1,4],[9,16]])
print("Matrix 1:",matt1,sep="\n")
print("Matrix Square Root:",np.sqrt(matt1),sep="\n")
print("Matrix Sum: ",np.sum(matt1))
print("Matrix Sum Column-wise:",np.sum(matt1,axis=1),sep="\n")
print("Matrix Sum Row-wise: ",np.sum(matt1,axis=0),sep="\n")
matt1.resize(4) # Changes the original matrix
print(np.matrix(matt1.reshape(2,2))) # Doesn't change the original matrix
print(matt1)

Matrix 1:
[[ 1  4]
 [ 9 16]]
Matrix Square Root:
[[1. 2.]
 [3. 4.]]
Matrix Sum:  30
Matrix Sum Column-wise:
[[ 5]
 [25]]
Matrix Sum Row-wise: 
[[10 20]]
[[ 1  4]
 [ 9 16]]
[ 1  4  9 16]


Question)
Using nested loops:
Approach:
- Define matrices A and B.
- Get the number of rows and columns of the matrices using the len() function.
- Initialize matrices C, D, and E with zeros using nested loops or list comprehension.
- Use nested loops or list comprehension to perform the element-wise addition, subtraction, and division of matrices.
- Print the resulting matrices C, D, and E.

In [50]:
# Write code for the above question here.

A=[[1,2,3],[4,5,6]]
B=[[7,8,9],[10,11,12]]
rows_of_A=len(A)
cols_of_A=len(A[0])
rows_of_B=len(B)
cols_of_B=len(B[0])
C=[[0]*cols_of_A]*rows_of_A
D=[[0]*cols_of_A]*rows_of_A
E=[[0]*cols_of_A]*rows_of_A

for i in range(rows_of_A):
    for j in range(cols_of_A):
        C[i][j]=A[i][j]+B[i][j]
        D[i][j]=A[i][j]-B[i][j]
        E[i][j]=A[i][j]/B[i][j]
print("Addition Result in C:",C,sep="\n")
print("Subtraction Result in D:",D,sep="\n")
print("Division Result in E:",E,sep="\n")

Addition Result in C:
[[14, 16, 18], [14, 16, 18]]
Subtraction Result in D:
[[-6, -6, -6], [-6, -6, -6]]
Division Result in E:
[[0.4, 0.45454545454545453, 0.5], [0.4, 0.45454545454545453, 0.5]]


In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5],[1,2],[3,4]])
print(arr1.dot(arr2))

arr3=np.array([1,2,3])
arr4=np.array([4,5,6])
print(np.dot(arr3,arr4)) # Vector dot product
print(np.cross(arr3,arr4)) # Vector cross product

arr5 = np.matrix('[4; 1; 6]') # Converts a Nx1 matrix to 1xN else returns the same matrix
print(arr5)
print(arr5.squeeze())

[[15 21]
 [39 54]]
32
[-3  6 -3]
[[4]
 [1]
 [6]]
[[4 1 6]]
